In [1]:
from PIL import Image
import numpy as np

def get_pixel_coordinates(image_path='./path/sample.png'):
    
    # Read the image
    image = Image.open(image_path)
    
    # Get the image size
    width, height = image.size

    # Get the pixel coordinates
    pixel_coordinates = []
    for y in range(height):
        for x in range(width):
            pixel_coordinates.append((x, y))

    return np.array(pixel_coordinates)


# Example usage

get_pixel_coordinates(image_path='./path/sample.png')


array([[   0,    0],
       [   1,    0],
       [   2,    0],
       ...,
       [2479,  405],
       [2480,  405],
       [2481,  405]])

In [2]:
def euclidean_distance(coordinates):
    
    # Convert the coordinates array to a NumPy array
    coordinates = np.array(coordinates)

    # Calculate the pairwise differences between coordinates
    diff = np.diff(coordinates, axis=0)

    # Square the differences and sum them along the axis
    squared_diff = np.square(diff)
    sum_squared_diff = np.sum(squared_diff, axis=1)

    # Take the square root to get the Euclidean distance
    distance = np.sqrt(sum_squared_diff)

    return distance

# Example usage

pixel_coordinates = get_pixel_coordinates(image_path='./path/sample.png')

euclidean_distance(pixel_coordinates)


array([1., 1., 1., ..., 1., 1., 1.])

In [4]:
def pixel_ratio(distance=[], object_size=20):
    
    return distance / object_size

# Example usage
d = euclidean_distance(pixel_coordinates)
pixel_ratio(distance=d, object_size=20)

array([0.05, 0.05, 0.05, ..., 0.05, 0.05, 0.05])